### ISSUE TITLE
Please add to stackage

### ISSUE THREAD

**Issue by newhoggy** [jwiegley/async-pool#11]
https://github.com/fpco/stackage

**Comment by jwiegley** [comment]
I don't maintain anything on Stackage, but I'm quite happy to let someone else take the lead on that.

**Comment by biesnecker** [comment]
I'm happy to be the maintainer for the stackage instance of this package (I'd really like to use it at work instead of recreating it, but all of our Haskell third party deps have to be in stackage). I'll go ahead and do that so long as you're open to accepting pull requests to this repo if updates need to be made to keep it in sync with stackage.

**Comment by newhoggy** [comment]
Thanks!
